#!/bin/sh
# Create a Synology Container Manager project (folders + docker-compose.yml).
# Run over SSH on the NAS:
#   curl -fsSL https://raw.githubusercontent.com/Qballjos/aio-media-server-manager/main/deploy/synology/install.sh | sudo sh
# Or: sudo sh install.sh
# Then open Container Manager → Project → Create and point at the project path.
#
# Downloads and media live in the DSM user home (File Station → Home), not
# /volume1/data, which mkdir creates outside any shared folder.

set -eu

VOLUME="${VOLUME:-/volume1}"
PROJECT="${PROJECT:-${VOLUME}/docker/aio-media-manager}"
BACKUPS="${BACKUPS:-${PROJECT}/backups}"
PUID="${PUID:-${SUDO_UID:-$(id -u)}}"
PGID="${PGID:-${SUDO_GID:-$(id -g)}}"
IMAGE="${IMAGE:-ghcr.io/qballjos/aio-media-server-manager:latest}"

dsm_user() {
  if [ -n "${HOME_USER:-}" ] && [ "${HOME_USER}" != "root" ]; then
    echo "${HOME_USER}"
    return
  fi
  if [ -n "${SUDO_USER:-}" ] && [ "${SUDO_USER}" != "root" ]; then
    echo "${SUDO_USER}"
    return
  fi
  uname_now="$(id -un 2>/dev/null || true)"
  if [ -n "${uname_now}" ] && [ "${uname_now}" != "root" ]; then
    echo "${uname_now}"
    return
  fi
  echo "admin"
}

real_dir() {
  readlink -f "$1" 2>/dev/null || echo "$1"
}

dsm_home() {
  user="$1"
  for candidate in \
    "${VOLUME}/homes/${user}" \
    "/var/services/homes/${user}" \
    "/volume1/homes/${user}"
  do
    if [ -d "${candidate}" ]; then
      real_dir "${candidate}"
      return 0
    fi
  done
  return 1
}

migrate_tree() {
  src="$1"
  dest="$2"
  [ -d "${src}" ] || return 0
  src_real="$(real_dir "${src}")"
  dest_real="$(real_dir "${dest}")"
  [ "${src_real}" != "${dest_real}" ] || return 0
  [ -e "${src}/downloads" ] || [ -e "${src}/media" ] || return 0

  echo "Moving downloads + media from ${src_real} → ${dest_real}"
  echo "(DSM File Station shows Home, not a raw /volume*/data folder.)"
  if command -v docker >/dev/null 2>&1; then
    docker stop aio-media-manager >/dev/null 2>&1 || true
  fi
  mkdir -p "${dest}"
  for name in downloads media; do
    if [ -e "${src}/${name}" ]; then
      if [ -e "${dest}/${name}" ]; then
        echo "  skip ${name}: already at ${dest}/${name}"
      else
        mv "${src}/${name}" "${dest}/${name}"
        echo "  moved ${name}"
      fi
    fi
  done
  rmdir "${src}" 2>/dev/null || true
}

DSM_USER="$(dsm_user)"

if [ -n "${DATA:-}" ]; then
  DATA_ROOT="${DATA}"
else
  if ! DSM_HOME="$(dsm_home "${DSM_USER}")"; then
    echo "Could not find a DSM home directory for user '${DSM_USER}'." >&2
    echo "Enable Control Panel → User & Group → Advanced → Enable user home service," >&2
    echo "or re-run with HOME_USER=<dsm-username> or DATA=/volume1/<share>/aio-media-manager." >&2
    exit 1
  fi
  DATA_ROOT="${DSM_HOME}/aio-media-manager"
  migrate_tree "${VOLUME}/data" "${DATA_ROOT}"
  if [ "${VOLUME}" != "/volume1" ]; then
    migrate_tree "/volume1/data" "${DATA_ROOT}"
  fi
fi

mkdir -p \
  "${PROJECT}/config/vpn" \
  "${PROJECT}/config/cloudflare" \
  "${BACKUPS}" \
  "${DATA_ROOT}/downloads" \
  "${DATA_ROOT}/media/movies" \
  "${DATA_ROOT}/media/tv"

chown -R "${PUID}:${PGID}" "${PROJECT}" "${DATA_ROOT}" "${BACKUPS}"

cat > "${PROJECT}/docker-compose.yml" <<EOF
# Generated by deploy/synology/install.sh — one AIO container only.
services:
  aio-media-manager:
    image: ${IMAGE}
    container_name: aio-media-manager
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8084:8084"
      - "8085:8085"
      - "8096:8096"
      - "8191:8191"
      - "5055:5055"
      - "6060:6060"
      - "6767:6767"
      - "6789:6789"
      - "6868:6868"
      - "7878:7878"
      - "8686:8686"
      - "8989:8989"
      - "9696:9696"
      - "9705:9705"
      - "32400:32400"
    volumes:
      - ${PROJECT}/config:/config
      - ${DATA_ROOT}:/data
      - ${BACKUPS}:/backups
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: UTC
      AMM_DOWNLOAD_DIR: /data/downloads
      AMM_MEDIA_DIR: /data/media
      AMM_VPN_ENABLED: "false"
      AMM_VPN_ENFORCE: "false"
      AMM_CLOUDFLARE_TUNNEL_ENABLED: "false"
      AMM_CLOUDFLARE_TUNNEL_TOKEN_FILE: /config/cloudflare/tunnel.token
      AMM_TRUSTED_PROXIES: ""
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
EOF

chmod 644 "${PROJECT}/docker-compose.yml"

echo
echo "Container Manager project files are ready."
echo "  Compose:    ${PROJECT}/docker-compose.yml"
echo "  Config:     ${PROJECT}/config"
echo "  Data:       ${DATA_ROOT}  (File Station → Home → aio-media-manager)"
echo "  Backups:    ${BACKUPS}  (config backups; set BACKUPS=/volume2/... for another volume)"
echo "  DSM user:   ${DSM_USER}"
echo "  PUID:PGID:  ${PUID}:${PGID}"
echo
echo "In DSM: Container Manager → Project → Create"
echo "  Name: aio-media-manager"
echo "  Path: ${PROJECT}"
echo "  Source: existing docker-compose.yml"
echo "Then start the project and open http://<nas-ip>:8080"
echo
echo "Optional (SSH): docker compose -f ${PROJECT}/docker-compose.yml pull"
