#!/bin/sh
# Create a Synology Container Manager project (folders + docker-compose.yml).
# Run over SSH on the NAS:
#   curl -fsSL https://raw.githubusercontent.com/Qballjos/aio-media-server-manager/main/deploy/synology/install.sh | sudo sh
# Or: sudo sh install.sh
# Then open Container Manager → Project → Create and point at the project path.

set -eu

VOLUME="${VOLUME:-/volume1}"
PROJECT="${PROJECT:-${VOLUME}/docker/aio-media-manager}"
DOWNLOADS="${DOWNLOADS:-${VOLUME}/downloads}"
MEDIA="${MEDIA:-${VOLUME}/media}"
PUID="${PUID:-${SUDO_UID:-$(id -u)}}"
PGID="${PGID:-${SUDO_GID:-$(id -g)}}"
IMAGE="${IMAGE:-ghcr.io/qballjos/aio-media-server-manager:latest}"

mkdir -p \
  "${PROJECT}/config/vpn" \
  "${DOWNLOADS}" \
  "${MEDIA}/movies" \
  "${MEDIA}/tv"

chown -R "${PUID}:${PGID}" "${PROJECT}" "${DOWNLOADS}" "${MEDIA}"

cat > "${PROJECT}/docker-compose.yml" <<EOF
# Generated by deploy/synology/install.sh — one AIO container only.
services:
  aio-media-manager:
    image: ${IMAGE}
    container_name: aio-media-manager
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ${PROJECT}/config:/config
      - ${DOWNLOADS}:/downloads
      - ${MEDIA}:/media
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      AMM_VPN_ENABLED: "false"
      AMM_VPN_ENFORCE: "false"
      AMM_TRUSTED_PROXIES: ""
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
EOF

chmod 644 "${PROJECT}/docker-compose.yml"

echo
echo "Container Manager project files are ready."
echo "  Compose:    ${PROJECT}/docker-compose.yml"
echo "  Config:     ${PROJECT}/config"
echo "  Downloads:  ${DOWNLOADS}"
echo "  Media:      ${MEDIA}"
echo "  PUID:PGID:  ${PUID}:${PGID}"
echo
echo "In DSM: Container Manager → Project → Create"
echo "  Name: aio-media-manager"
echo "  Path: ${PROJECT}"
echo "  Source: existing docker-compose.yml"
echo "Then start the project and open http://<nas-ip>:8080"
echo
echo "Optional (SSH): docker compose -f ${PROJECT}/docker-compose.yml pull"
