from __future__ import annotations

import glob
import os
import shutil
import subprocess
from pathlib import Path

from applications.arr import ArrApplication
from applications.base import SimpleApplication
from applications.install_helpers import child_python, create_venv, venv_bin, write_runner
from applications.manifest import AppCategory, AppManifest, AppTier, InstallMethod
from core.installer import AppInstaller, InstallResult
from core.installer.arch import PlatformArch, detect_system_arch


class LidarrApp(ArrApplication):
    manifest = AppManifest(
        name="lidarr",
        display_name="Lidarr",
        description="Music collection automation for Usenet and BitTorrent.",
        github_repo="Lidarr/Lidarr",
        upstream_url="https://github.com/Lidarr/Lidarr",
        tier=AppTier.OPTIONAL,
        category=AppCategory.AUTOMATION,
        default_port=8686,
        executable_name="Lidarr",
        supported_architectures=("x86_64", "arm64", "armv7"),
        install_method=InstallMethod.GITHUB_RELEASE,
        preferred_patterns=("linux",),
        optional_dependencies=("prowlarr", "sabnzbd", "qbittorrent"),
        health_path="/ping",
    )


class NzbgetApp(SimpleApplication):
    manifest = AppManifest(
        name="nzbget",
        display_name="NZBGet",
        description="Alternative Usenet downloader with a web interface.",
        github_repo="nzbgetcom/nzbget",
        upstream_url="https://github.com/nzbgetcom/nzbget",
        tier=AppTier.CORE,
        category=AppCategory.DOWNLOADING,
        default_port=6789,
        executable_name="nzbget",
        supported_architectures=("x86_64", "arm64", "armv7"),
        install_method=InstallMethod.GITHUB_RELEASE,
        # Official GitHub assets include a makeself .run installer (not the daemon)
        # and arch-specific .deb packages. Prefer the .deb for this Debian image.
        preferred_patterns=(r"\.deb$",),
        health_path="/jsonrpc",
    )

    def config_file(self) -> Path:
        return self.config_dir / "nzbget.conf"

    def post_install(self) -> None:
        self._ensure_config()

    def working_directory(self) -> Path | None:
        exe = self.executable_path()
        if exe is not None:
            return exe.parent
        return self.install_dir

    def extra_env(self) -> dict[str, str]:
        return {"TERM": "linux"}

    def start_args(self) -> list[str]:
        self._ensure_config()
        complete = self.download_dir / "complete"
        incomplete = self.download_dir / "incomplete"
        args = [
            "--configfile",
            str(self.config_file()),
            "--server",
            "--option",
            f"ControlIP=0.0.0.0",
            "--option",
            f"ControlPort={self.port}",
            "--option",
            f"MainDir={self.data_dir}",
            "--option",
            f"DestDir={complete}",
            "--option",
            f"InterDir={incomplete}",
            "--option",
            "OutputMode=log",
            "--option",
            "DaemonUsername=root",
        ]
        from core.shared_credentials import shared_admin_credentials

        creds = shared_admin_credentials()
        if creds:
            user, password = creds
            args.extend(
                [
                    "--option",
                    f"ControlUsername={user}",
                    "--option",
                    f"ControlPassword={password}",
                ]
            )
        webui = self._bundled_webui()
        if webui is not None:
            args.extend(["--option", f"WebDir={webui}"])
        return args

    def _ensure_config(self) -> None:
        self.config_dir.mkdir(parents=True, exist_ok=True)
        self.data_dir.mkdir(parents=True, exist_ok=True)
        dest = self.config_file()
        if dest.is_file():
            return
        template = self._bundled_conf()
        if template is not None:
            shutil.copy2(template, dest)
            return
        dest.write_text(
            "\n".join(
                [
                    "# Generated by AIO Media Server Manager",
                    f"MainDir={self.data_dir}",
                    f"DestDir={self.download_dir / 'complete'}",
                    f"InterDir={self.download_dir / 'incomplete'}",
                    "ControlIP=0.0.0.0",
                    f"ControlPort={self.port}",
                    *self._control_auth_lines(),
                    "OutputMode=log",
                    "DaemonUsername=root",
                    "",
                ]
            ),
            encoding="utf-8",
        )

    def _control_auth_lines(self) -> list[str]:
        from core.shared_credentials import shared_admin_credentials

        creds = shared_admin_credentials()
        if creds:
            user, password = creds
            return [f"ControlUsername={user}", f"ControlPassword={password}"]
        return ["ControlUsername=nzbget", "ControlPassword=tegbzn6789"]

    def _bundled_conf(self) -> Path | None:
        if not self.install_dir.exists():
            return None
        for candidate in self.install_dir.rglob("nzbget.conf"):
            if candidate.is_file() and candidate != self.config_file():
                return candidate
        return None

    def _bundled_webui(self) -> Path | None:
        if not self.install_dir.exists():
            return None
        for candidate in self.install_dir.rglob("webui"):
            if candidate.is_dir():
                return candidate
        return None


class BazarrApp(SimpleApplication):
    manifest = AppManifest(
        name="bazarr",
        display_name="Bazarr",
        description="Subtitle management companion for Sonarr and Radarr.",
        github_repo="morpheus65535/bazarr",
        upstream_url="https://github.com/morpheus65535/bazarr",
        tier=AppTier.RECOMMENDED,
        category=AppCategory.SUBTITLES,
        default_port=6767,
        executable_name="bazarr",
        supported_architectures=("x86_64", "arm64"),
        install_method=InstallMethod.GITHUB_RELEASE,
        preferred_patterns=(r"bazarr\.zip$",),
        optional_dependencies=("sonarr", "radarr"),
        health_path="/api/system/health",
    )

    def executable_path(self) -> Path | None:
        runner = self.install_dir / "run-bazarr"
        if runner.is_file():
            return runner
        script = self.install_dir / "bazarr.py"
        if script.is_file():
            return script
        return super().executable_path()

    def start_command(self) -> list[str]:
        self._ensure_runtime()
        self._write_runner()
        return super().start_command()

    def _venv_python(self) -> Path:
        return venv_bin(self.install_dir / "venv", "python")

    def _pillow_ok(self, python: Path) -> bool:
        if not python.is_file():
            return False
        probe = subprocess.run(
            [str(python), "-c", "import PIL"],
            capture_output=True,
            text=True,
        )
        return probe.returncode == 0

    def _ensure_runtime(self) -> Path:
        venv_python = self._venv_python()
        if venv_python.is_file() and self._pillow_ok(venv_python):
            return venv_python
        venv_dir = create_venv(self.install_dir, python=child_python())
        pip = venv_bin(venv_dir, "pip")
        requirements = self.install_dir / "requirements.txt"
        cmd = [str(pip), "install"]
        if requirements.is_file():
            cmd.extend(["-r", str(requirements)])
        else:
            cmd.extend(["Pillow>=9.0.0", "lxml>=4.3.0", "numpy>=1.12.0,<2.4.0", "setuptools"])
        subprocess.run(cmd, check=True, capture_output=True, text=True)
        return venv_bin(venv_dir, "python")

    def _write_runner(self) -> Path | None:
        script = self.install_dir / "bazarr.py"
        if not script.is_file():
            return None
        venv_python = self._venv_python()
        interpreter = str(venv_python) if venv_python.is_file() else child_python()
        lines = ["#!/bin/sh"]
        if Path("/opt/python3.13/lib").is_dir():
            lines.append(
                'export LD_LIBRARY_PATH="/opt/python3.13/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"'
            )
        lines.append(f'exec "{interpreter}" "{script}" "$@"')
        return write_runner(self.install_dir / "run-bazarr", lines)

    def install(self) -> InstallResult:
        installer = AppInstaller()
        result = installer.install_from_github(
            repo=self.github_repo,
            app_name=self.name,
            executable_name="bazarr.py",
            preferred_patterns=self.preferred_patterns(),
        )
        self._ensure_runtime()
        self._write_runner()
        self.post_install()
        return result

    def start_args(self) -> list[str]:
        self._seed_auth()
        return ["--no-update", "--config", str(self.config_dir), "--port", str(self.port)]

    def post_install(self) -> None:
        self._seed_auth()

    def _seed_auth(self) -> None:
        from core.integrations.local_auth import patch_bazarr_auth_yaml
        from core.shared_credentials import shared_admin_credentials

        creds = shared_admin_credentials()
        if not creds:
            return
        username, password = creds
        patch_bazarr_auth_yaml(self.config_dir / "config" / "config.yaml", username, password)


class RecyclarrApp(SimpleApplication):
    manifest = AppManifest(
        name="recyclarr",
        display_name="Recyclarr",
        description="CLI that syncs TRaSH Guides quality profiles into Sonarr and Radarr.",
        github_repo="Recyclarr/Recyclarr",
        upstream_url="https://github.com/Recyclarr/Recyclarr",
        tier=AppTier.RECOMMENDED,
        category=AppCategory.OPTIMIZATION,
        default_port=19001,
        executable_name="recyclarr",
        supported_architectures=("x86_64", "arm64"),
        install_method=InstallMethod.GITHUB_RELEASE,
        preferred_patterns=("linux",),
        optional_dependencies=("sonarr", "radarr"),
        health_path="/",
        daemon=False,
    )

    def start_args(self) -> list[str]:
        # Recyclarr 8 removed --app-data; config dir is RECYCLARR_CONFIG_DIR.
        return ["sync"]

    def extra_env(self) -> dict[str, str]:
        return {"RECYCLARR_CONFIG_DIR": str(self.config_dir)}

    def post_install(self) -> None:
        from applications.catalog import ApplicationCatalog
        from core.integrations.credentials import get_application_api_key
        from core.recyclarr import write_recyclarr_config

        catalog = ApplicationCatalog()
        sonarr_port = catalog.get("sonarr").port if catalog.has("sonarr") else 8989
        radarr_port = catalog.get("radarr").port if catalog.has("radarr") else 7878
        write_recyclarr_config(
            self.config_dir,
            sonarr_url=f"http://127.0.0.1:{sonarr_port}",
            sonarr_key=get_application_api_key("sonarr") or "",
            radarr_url=f"http://127.0.0.1:{radarr_port}",
            radarr_key=get_application_api_key("radarr") or "",
        )


class ProfilarrApp(SimpleApplication):
    manifest = AppManifest(
        name="profilarr",
        display_name="Profilarr",
        description="Quality profile management for the *Arr applications.",
        github_repo="Dictionarry-Hub/profilarr",
        upstream_url="https://github.com/Dictionarry-Hub/profilarr",
        tier=AppTier.RECOMMENDED,
        category=AppCategory.OPTIMIZATION,
        default_port=6868,
        executable_name="profilarr",
        supported_architectures=("x86_64", "arm64"),
        install_method=InstallMethod.GITHUB_RELEASE,
        optional_dependencies=("sonarr", "radarr"),
        health_path="/",
    )

    def extra_env(self) -> dict[str, str]:
        sqlite = _sqlite_library()
        env = {
            "PORT": str(self.port),
            "HOST": "0.0.0.0",
            "TZ": "Etc/UTC",
            "AUTH": "local",
            "APP_BASE_PATH": str(self.config_dir),
            "DENO_DIR": str(self.install_dir / "deno-cache"),
        }
        if sqlite:
            env["DENO_SQLITE_PATH"] = sqlite
        return env

    def working_directory(self) -> Path | None:
        return self.install_dir

    def install(self) -> InstallResult:
        installer = AppInstaller()
        result = installer.install_from_github_source(
            self.github_repo,
            self.name,
            "deno.jsonc",
        )
        deno = _ensure_deno(self.install_dir / "bin")
        build_dir = self.install_dir / "dist" / "build"
        env = {**os.environ, **self.extra_env(), "APP_BASE_PATH": "dist/build"}
        subprocess.run(
            [str(deno), "ci"],
            cwd=self.install_dir,
            check=True,
            capture_output=True,
            text=True,
            env=env,
        )
        subprocess.run(
            [str(deno), "run", "-A", "vite", "build"],
            cwd=self.install_dir,
            check=True,
            capture_output=True,
            text=True,
            env=env,
        )
        compiled = self.install_dir / "profilarr"
        target = (
            "aarch64-unknown-linux-gnu"
            if detect_system_arch() == PlatformArch.ARM64
            else "x86_64-unknown-linux-gnu"
        )
        mod = self.install_dir / "dist" / "build" / "mod.ts"
        if mod.is_file():
            compile = subprocess.run(
                [
                    str(deno),
                    "compile",
                    "--no-check",
                    "--allow-all",
                    "--target",
                    target,
                    "--output",
                    str(compiled),
                    str(mod),
                ],
                cwd=self.install_dir,
                capture_output=True,
                text=True,
                env=env,
            )
            if compile.returncode != 0 or not compiled.is_file():
                write_runner(
                    compiled,
                    [
                        "#!/bin/sh",
                        f'exec "{deno}" run --allow-all "{mod}" "$@"',
                    ],
                )
        else:
            write_runner(
                compiled,
                [
                    "#!/bin/sh",
                    f'cd "{self.install_dir}"',
                    f'exec "{deno}" task preview "$@"',
                ],
            )
        static_src = build_dir / "static"
        if not static_src.is_dir() and (build_dir / "client").is_dir():
            static_src = build_dir / "client"
        static_dest = self.install_dir / "static"
        if static_src.is_dir():
            if static_dest.exists():
                shutil.rmtree(static_dest)
            shutil.copytree(static_src, static_dest)
        server_js = build_dir / "server.js"
        if server_js.is_file():
            shutil.copy2(server_js, self.install_dir / "server.js")
        self.post_install()
        return result


class NeutarrApp(SimpleApplication):
    manifest = AppManifest(
        name="neutarr",
        display_name="NeutArr",
        description="Hunts missing media and quality upgrades across the *Arr stack.",
        github_repo="I-am-PUID-0/NeutArr",
        upstream_url="https://github.com/I-am-PUID-0/NeutArr",
        tier=AppTier.RECOMMENDED,
        category=AppCategory.OPTIMIZATION,
        default_port=9705,
        executable_name="neutarr",
        supported_architectures=("x86_64", "arm64"),
        install_method=InstallMethod.GITHUB_RELEASE,
        optional_dependencies=("sonarr", "radarr"),
        health_path="/",
    )

    def extra_env(self) -> dict[str, str]:
        return {
            "NEUTARR_CONFIG_DIR": str(self.config_dir),
            "CONFIG_DIR": str(self.config_dir),
            "NEUTARR_PORT": str(self.port),
            "PORT": str(self.port),
            "FLASK_HOST": "0.0.0.0",
            "TZ": "Etc/UTC",
            "PYTHONPATH": str(self.install_dir),
        }

    def install(self) -> InstallResult:
        installer = AppInstaller()
        result = installer.install_from_github_source(
            self.github_repo,
            self.name,
            "main.py",
        )
        venv_dir = create_venv(self.install_dir)
        pip = venv_bin(venv_dir, "pip")
        subprocess.run(
            [
                str(pip),
                "install",
                "flask>=3.1.3,<4.0.0",
                "requests>=2.31.0,<3.0.0",
                "waitress>=3.0.1,<4.0.0",
                "bcrypt>=4.1.2,<6.0.0",
                "pyjwt>=2.9.0,<3.0.0",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        frontend = self.install_dir / "frontend"
        npm = shutil.which("npm")
        if npm and (frontend / "package.json").is_file():
            subprocess.run([npm, "ci"], cwd=frontend, check=True, capture_output=True, text=True)
            subprocess.run([npm, "run", "build"], cwd=frontend, check=True, capture_output=True, text=True)
        python = venv_bin(venv_dir, "python")
        runner = self.install_dir / "neutarr"
        write_runner(
            runner,
            [
                "#!/bin/sh",
                f'cd "{self.install_dir}"',
                f'export PYTHONPATH="{self.install_dir}"',
                f'exec "{python}" "{self.install_dir / "main.py"}" "$@"',
            ],
        )
        self.post_install()
        return result


def _sqlite_library() -> str | None:
    matches = glob.glob("/usr/lib/*/libsqlite3.so.0") + glob.glob("/usr/lib/libsqlite3.so.0")
    return matches[0] if matches else None


def _ensure_deno(bin_dir: Path) -> Path:
    bin_dir.mkdir(parents=True, exist_ok=True)
    deno = bin_dir / "deno"
    if deno.is_file():
        return deno
    slug = (
        "aarch64-unknown-linux-gnu"
        if detect_system_arch() == PlatformArch.ARM64
        else "x86_64-unknown-linux-gnu"
    )
    installer = AppInstaller()
    cache = installer.settings.cache_dir / "downloads"
    cache.mkdir(parents=True, exist_ok=True)
    archive = cache / f"deno-{slug}.zip"
    installer.download_file(
        f"https://github.com/denoland/deno/releases/latest/download/deno-{slug}.zip",
        archive,
    )
    from core.installer.extractor import ArchiveExtractor

    staging = bin_dir / ".deno-extract"
    if staging.exists():
        shutil.rmtree(staging)
    ArchiveExtractor.extract(archive, staging, strip_single_wrapper=True)
    found = next(staging.rglob("deno"), None)
    if found is None:
        raise FileNotFoundError("Deno binary missing from official release zip.")
    shutil.copy2(found, deno)
    deno.chmod(deno.stat().st_mode | 0o755)
    shutil.rmtree(staging, ignore_errors=True)
    return deno
