"""Write starter configs for Recyclarr, Profilarr, NeutArr, and Unpackerr."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Recyclarr v8 guide-backed TRaSH profile IDs.
_SONARR_WEB_1080P = "72dae194fc92bf828f32cde7744e51a1"
_SONARR_ANIME_REMUX_1080P = "20e0fc959f1f1704bed501f23bdae76f"
_RADARR_HD_BLURAY_WEB = "d1d67249d3890e49bc12e275d989a7e9"


def write_recyclarr_config(
    config_dir: Path,
    *,
    sonarr_url: str,
    sonarr_key: str,
    radarr_url: str,
    radarr_key: str,
) -> Path:
    path = Path(config_dir) / "recyclarr.yml"
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and "trash_id" in path.read_text(encoding="utf-8"):
        return path
    body = f"""# yaml-language-server: $schema=https://schemas.recyclarr.dev/v8/config-schema.json
# Generated by AIO Media Server Manager — Recyclarr v8 / TRaSH Guides.
# WEB-1080p (TV), Anime Remux-1080p (same Sonarr), HD Bluray + WEB (movies).

sonarr:
  tv:
    base_url: {sonarr_url}
    api_key: {sonarr_key}
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    quality_definition:
      type: series
    quality_profiles:
      - trash_id: {_SONARR_WEB_1080P}  # WEB-1080p
        reset_unmatched_scores:
          enabled: true
    media_naming:
      series: plex-tv
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default
  anime:
    base_url: {sonarr_url}
    api_key: {sonarr_key}
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    quality_definition:
      type: anime
    quality_profiles:
      - trash_id: {_SONARR_ANIME_REMUX_1080P}  # [Anime] Remux-1080p
        reset_unmatched_scores:
          enabled: true

radarr:
  movies:
    base_url: {radarr_url}
    api_key: {radarr_key}
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    quality_definition:
      type: movie
    quality_profiles:
      - trash_id: {_RADARR_HD_BLURAY_WEB}  # HD Bluray + WEB
        reset_unmatched_scores:
          enabled: true
    media_naming:
      folder: plex-tmdb
      movie:
        rename: true
        standard: plex-tmdb
"""
    path.write_text(body, encoding="utf-8")
    logger.info("Wrote Recyclarr TRaSH config at %s", path)
    return path


def write_profilarr_config(
    config_dir: Path,
    *,
    sonarr_url: str,
    sonarr_key: str,
    radarr_url: str,
    radarr_key: str,
    lidarr_url: str = "",
    lidarr_key: str = "",
) -> Path:
    path = Path(config_dir) / "config.yml"
    path.parent.mkdir(parents=True, exist_ok=True)
    (Path(config_dir) / "imports").mkdir(parents=True, exist_ok=True)
    (Path(config_dir) / "exports").mkdir(parents=True, exist_ok=True)
    if path.exists() and "base_url:" in path.read_text(encoding="utf-8"):
        return path
    lidarr_block = ""
    if lidarr_url:
        lidarr_block = (
            "lidarr:\n"
            f'  - name: "Lidarr (AMM)"\n'
            f'    base_url: "{lidarr_url}"\n'
            f'    api_key: "{lidarr_key}"\n'
        )
    body = f"""# Generated by AIO Media Server Manager — Dictionarry / Profilarr instances.
instances:
  sonarr:
    - name: "Sonarr (AMM)"
      base_url: "{sonarr_url}"
      api_key: "{sonarr_key}"
  radarr:
    - name: "Radarr (AMM)"
      base_url: "{radarr_url}"
      api_key: "{radarr_key}"
{lidarr_block}settings:
  export_path: "{Path(config_dir) / 'exports'}"
  import_path: "{Path(config_dir) / 'imports'}"
  ansi_colors: true
  sync_custom_formats: true
  sync_quality_profiles: true
  backup_before_sync: true
"""
    path.write_text(body, encoding="utf-8")
    logger.info("Wrote Profilarr config at %s", path)
    return path


def write_neutarr_config(
    config_dir: Path,
    *,
    sonarr_url: str,
    sonarr_key: str,
    radarr_url: str,
    radarr_key: str,
    lidarr_url: str = "",
    lidarr_key: str = "",
) -> Path:
    root = Path(config_dir)
    root.mkdir(parents=True, exist_ok=True)
    general = root / "general.json"
    if not general.exists():
        general.write_text(
            json.dumps(
                {
                    "debug_mode": False,
                    "log_refresh_interval_seconds": 30,
                    "ui_theme": "dark",
                    "check_for_updates": True,
                    "enable_notifications": False,
                    "notification_level": "info",
                    "local_access_bypass": True,
                    "proxy_auth_bypass": False,
                    "local_bypass_cidrs": [
                        "127.0.0.0/8",
                        "::1/128",
                        "10.0.0.0/8",
                        "172.16.0.0/12",
                        "192.168.0.0/16",
                    ],
                    "stateful_management_hours": 168,
                    "command_wait_delay": 1,
                    "command_wait_attempts": 600,
                    "minimum_download_queue_size": 1,
                    "api_timeout": 120,
                    "ssl_verify": False,
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

    _write_json_if_missing(
        root / "sonarr.json",
        {
            "instances": [
                {
                    "name": "Sonarr (AMM)",
                    "api_url": sonarr_url,
                    "api_key": sonarr_key,
                    "enabled": bool(sonarr_url and sonarr_key),
                }
            ],
            "hunt_missing_items": 1,
            "hunt_upgrade_items": 1,
            "upgrade_mode": "episodes",
            "hunt_missing_mode": "episodes",
            "sleep_duration": 900,
            "monitored_only": True,
            "skip_future_episodes": True,
            "hourly_cap": 20,
        },
    )
    _write_json_if_missing(
        root / "radarr.json",
        {
            "instances": [
                {
                    "name": "Radarr (AMM)",
                    "api_url": radarr_url,
                    "api_key": radarr_key,
                    "enabled": bool(radarr_url and radarr_key),
                }
            ],
            "hunt_missing_movies": 1,
            "hunt_upgrade_movies": 1,
            "sleep_duration": 900,
            "monitored_only": True,
            "skip_future_releases": True,
            "release_types": ["physical"],
            "release_type": "physical",
            "hourly_cap": 20,
        },
    )
    if lidarr_url:
        _write_json_if_missing(
            root / "lidarr.json",
            {
                "instances": [
                    {
                        "name": "Lidarr (AMM)",
                        "api_url": lidarr_url,
                        "api_key": lidarr_key,
                        "enabled": bool(lidarr_key),
                    }
                ],
                "hunt_missing_mode": "artist",
                "hunt_missing_items": 1,
                "hunt_upgrade_items": 0,
                "sleep_duration": 900,
                "monitored_only": True,
                "hourly_cap": 20,
                "skip_future_releases": True,
            },
        )
    logger.info("Wrote NeutArr hunt configs under %s", root)
    return general


def write_unpackerr_config(
    config_dir: Path,
    *,
    complete_paths: list[str],
    sonarr_url: str = "",
    sonarr_key: str = "",
    radarr_url: str = "",
    radarr_key: str = "",
    lidarr_url: str = "",
    lidarr_key: str = "",
) -> Path:
    path = Path(config_dir) / "unpackerr.conf"
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        return path
    lines = [
        "# Generated by AIO Media Server Manager",
        "debug = false",
        "",
    ]
    for url, key, header in (
        (sonarr_url, sonarr_key, "sonarr"),
        (radarr_url, radarr_key, "radarr"),
        (lidarr_url, lidarr_key, "lidarr"),
    ):
        if not url:
            continue
        lines.extend(
            [
                f"[[{header}]]",
                f'url = "{url}"',
                f'api_key = "{key}"',
                "",
            ]
        )
    for folder in complete_paths:
        lines.extend(
            [
                "[[folder]]",
                f'path = "{folder}"',
                'delete_after = "10m"',
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Wrote Unpackerr starter config at %s", path)
    return path


def _write_json_if_missing(path: Path, payload: dict[str, Any]) -> None:
    if path.exists():
        return
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
