"""Write starter configs for Recyclarr, Profilarr, and NeutArr after install."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def write_recyclarr_config(
    config_dir: Path,
    *,
    sonarr_url: str,
    sonarr_key: str,
    radarr_url: str,
    radarr_key: str,
) -> Path:
    path = Path(config_dir) / "recyclarr.yml"
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        return path
    body = (
        "# Generated by AIO Media Server Manager — TRaSH sync via Recyclarr.\n"
        "sonarr:\n"
        "  tv:\n"
        f"    base_url: {sonarr_url}\n"
        f"    api_key: {sonarr_key}\n"
        "radarr:\n"
        "  movies:\n"
        f"    base_url: {radarr_url}\n"
        f"    api_key: {radarr_key}\n"
    )
    path.write_text(body, encoding="utf-8")
    logger.info("Wrote Recyclarr starter config at %s", path)
    return path


def write_profilarr_config(
    config_dir: Path,
    *,
    sonarr_url: str,
    sonarr_key: str,
    radarr_url: str,
    radarr_key: str,
) -> Path:
    path = Path(config_dir) / "profilarr.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        return path
    payload: dict[str, Any] = {
        "sonarr": [{"name": "Sonarr (AMM)", "url": sonarr_url, "api_key": sonarr_key}],
        "radarr": [{"name": "Radarr (AMM)", "url": radarr_url, "api_key": radarr_key}],
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    logger.info("Wrote Profilarr starter config at %s", path)
    return path


def write_neutarr_config(
    config_dir: Path,
    *,
    sonarr_url: str,
    sonarr_key: str,
    radarr_url: str,
    radarr_key: str,
) -> Path:
    path = Path(config_dir) / "apps.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        return path
    payload = {
        "sonarr": [{"name": "Sonarr (AMM)", "url": sonarr_url, "api_key": sonarr_key, "enabled": True}],
        "radarr": [{"name": "Radarr (AMM)", "url": radarr_url, "api_key": radarr_key, "enabled": True}],
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    logger.info("Wrote NeutArr starter config at %s", path)
    return path
